name: Auto-Translate Korean Blog Posts

on:
  push:
    branches:
      - main
    paths:
      - 'content/posts/**/*.mdx'
  workflow_dispatch: # Allow manual trigger for testing

jobs:
  translate:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for better git operations

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Detect changed MDX files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            content/posts/**/*.mdx
          files_ignore: |
            content/posts/**/*.en.mdx

      - name: List changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Changed MDX files:"
          echo "${{ steps.changed-files.outputs.all_changed_files }}"

      - name: Translate MDX files
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # Make script executable
          chmod +x scripts/translate-mdx.js

          # Translate each changed file
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "Translating: $file"
            node scripts/translate-mdx.js "$file" || echo "Warning: Translation failed for $file"
          done

      - name: Check for translated files
        id: check-translations
        run: |
          if git status --porcelain | grep -q '\.en\.mdx$'; then
            echo "has_translations=true" >> $GITHUB_OUTPUT
            echo "Translated files found:"
            git status --porcelain | grep '\.en\.mdx$' || true
          else
            echo "has_translations=false" >> $GITHUB_OUTPUT
            echo "No new translations generated"
          fi

      - name: Configure git
        if: steps.check-translations.outputs.has_translations == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push translations
        if: steps.check-translations.outputs.has_translations == 'true'
        run: |
          # Add only .en.mdx files
          git add content/posts/**/*.en.mdx

          # Get list of translated files for commit message
          translated_files=$(git diff --cached --name-only | grep '\.en\.mdx$' | xargs -I {} basename {} .en.mdx | paste -sd "," -)

          # Create commit
          git commit -m "chore: auto-translate blog posts to English

Translated files: ${translated_files}

Generated with GitHub Actions auto-translation workflow"

          # Push to main branch
          git push origin main

      - name: Summary
        if: always()
        run: |
          echo "### Translation Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [ "${{ steps.changed-files.outputs.any_changed }}" == "true" ]; then
            echo "**Changed files detected:** ${{ steps.changed-files.outputs.all_changed_files_count }}" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Files:" >> $GITHUB_STEP_SUMMARY
            for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              echo "- \`$file\`" >> $GITHUB_STEP_SUMMARY
            done
          else
            echo "No MDX files were changed in this push." >> $GITHUB_STEP_SUMMARY
          fi

          echo "" >> $GITHUB_STEP_SUMMARY

          if [ "${{ steps.check-translations.outputs.has_translations }}" == "true" ]; then
            echo "**✅ Translations generated and committed**" >> $GITHUB_STEP_SUMMARY
          else
            echo "**ℹ️ No new translations generated**" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Possible reasons:" >> $GITHUB_STEP_SUMMARY
            echo "- Files are already translated" >> $GITHUB_STEP_SUMMARY
            echo "- Translation API errors occurred" >> $GITHUB_STEP_SUMMARY
            echo "- Only .en.mdx files were modified" >> $GITHUB_STEP_SUMMARY
          fi
