name: Deploy Blog to GitHub Pages
on:
  push:
    branches: ["main"]
    paths:
      - "src/**"
      - "next.config.ts"
      - "package.json"
      - "package-lock.json"
      - "tsconfig.json"
      - "articles/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: package-lock.json
      
      - name: Install dependencies
        run: npm i
      
      - name: Build with Next.js
        run: npm run build
      
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
